### ISSUE TITLE
Application is not using DaggerAndroid features

### ISSUE THREAD

**Issue by jmcaldera** [KiranKala/ReactiveScorecard#1]
App is using dagger2, but not dagger android, ie: there's no application class that extends from DaggerApplication.

AppComponent should add AndroidInjectionModule or AndroidSupportInjectionModule as one of its modules. Also it should have an internal interface or abstract class annotated with @Component.Builder (refer to example links)

Injection into Activities or fragments should be done by calling AndroidInjection.inject(this) and not by creating the component instance by itself (this is handled by Application class).

Also add dagger-android-processor annotationProcessor

**Comment by KiranKala** [comment]
- Created application class which extends DaggerApplication.
- Added AndroidInjectionModule to AppComponent class and created an interface with @Component.Builder (annotation)
- Added dagger-android-processor annotationProcessor
